"""empty message

Revision ID: 105b079a1123
Revises: 82817ee06be6
Create Date: 2020-11-06 15:43:41.490280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '105b079a1123'
down_revision = '82817ee06be6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoiceitems', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoiceitems', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
