"""extra migration.

Revision ID: 332948a6083c
Revises: 1007aed5b0b0
Create Date: 2020-09-28 16:49:33.977321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '332948a6083c'
down_revision = '1007aed5b0b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('invoice_date2', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'invoice_date2')
    # ### end Alembic commands ###
