"""empty message

Revision ID: 3fa09699abee
Revises: d0c4cbdac4eb
Create Date: 2020-10-13 14:29:41.622630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fa09699abee'
down_revision = 'd0c4cbdac4eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed_email_otp', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('confirmed_phone', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('confirmed_phone_on', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('confirmed_phone_otp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed_phone_otp')
    op.drop_column('users', 'confirmed_phone_on')
    op.drop_column('users', 'confirmed_phone')
    op.drop_column('users', 'confirmed_email_otp')
    # ### end Alembic commands ###
