"""empty message

Revision ID: 6a59736e6af5
Revises: 8ddbfa8bcd0a
Create Date: 2020-11-06 10:02:20.821919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a59736e6af5'
down_revision = '8ddbfa8bcd0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoiceitems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('payed', sa.Boolean(), nullable=True),
    sa.Column('invoice_version', sa.Integer(), nullable=True),
    sa.Column('invoiceid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['invoiceid'], ['invoices.invoiceid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('billdebts', sa.Column('sms', sa.Boolean(), nullable=True))
    op.add_column('billdebts', sa.Column('sms_attempts', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billdebts', 'sms_attempts')
    op.drop_column('billdebts', 'sms')
    op.drop_table('invoiceitems')
    # ### end Alembic commands ###
