"""empty message

Revision ID: 6b7e87b102ee
Revises: 
Create Date: 2020-09-28 19:51:17.318273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b7e87b102ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('userid')
    )
    op.create_table('friends',
    sa.Column('friendshipid', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('frienduserid', sa.Integer(), nullable=False),
    sa.Column('statusid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['frienduserid'], ['users.userid'], ),
    sa.ForeignKeyConstraint(['userid'], ['users.userid'], ),
    sa.PrimaryKeyConstraint('friendshipid')
    )
    op.create_table('invoices',
    sa.Column('invoiceid', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('frienduserid', sa.Integer(), nullable=False),
    sa.Column('statusid', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_due', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('invoice_version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['frienduserid'], ['users.userid'], ),
    sa.ForeignKeyConstraint(['userid'], ['users.userid'], ),
    sa.PrimaryKeyConstraint('invoiceid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoices')
    op.drop_table('friends')
    op.drop_table('users')
    # ### end Alembic commands ###
