"""empty message

Revision ID: 6e1c55e8dfc7
Revises: 3fa09699abee
Create Date: 2020-10-23 10:21:01.205486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e1c55e8dfc7'
down_revision = '3fa09699abee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('credits', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('usertype', sa.Integer(), nullable=True))
    op.execute("UPDATE users SET usertype = 2")
    op.execute("UPDATE users SET credits = 100")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'usertype')
    op.drop_column('users', 'credits')
    # ### end Alembic commands ###
