"""empty message

Revision ID: 89f88a8b9472
Revises: cebf9212a4e8
Create Date: 2020-11-07 16:24:57.228810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89f88a8b9472'
down_revision = 'cebf9212a4e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bills', 'token')
    # ### end Alembic commands ###
