"""empty message

Revision ID: 8ddbfa8bcd0a
Revises: d8cb141c640a
Create Date: 2020-11-03 15:10:24.660263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ddbfa8bcd0a'
down_revision = 'd8cb141c640a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('amount_payee', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bills', 'amount_payee')
    # ### end Alembic commands ###
