"""empty message

Revision ID: cebf9212a4e8
Revises: 105b079a1123
Create Date: 2020-11-06 15:45:20.119475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cebf9212a4e8'
down_revision = '105b079a1123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoiceitems', sa.Column('price', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoiceitems', 'price')
    # ### end Alembic commands ###
