"""empty message

Revision ID: cfb487136f33
Revises: f9bd8295992f
Create Date: 2020-10-29 11:18:25.452194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfb487136f33'
down_revision = 'f9bd8295992f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('billdebts_invoiceid_fkey', 'billdebts', type_='foreignkey')
    op.drop_column('billdebts', 'invoiceid')
    op.add_column('invoices', sa.Column('billdebtid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'invoices', 'billdebts', ['billdebtid'], ['billdebtid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'billdebtid')
    op.add_column('billdebts', sa.Column('invoiceid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('billdebts_invoiceid_fkey', 'billdebts', 'invoices', ['invoiceid'], ['invoiceid'])
    # ### end Alembic commands ###
