"""empty message

Revision ID: d0c4cbdac4eb
Revises: 6b7e87b102ee
Create Date: 2020-10-09 16:33:59.362627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0c4cbdac4eb'
down_revision = '6b7e87b102ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed_email', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('confirmed_email_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed_email_on')
    op.drop_column('users', 'confirmed_email')
    # ### end Alembic commands ###
