"""empty message

Revision ID: d8cb141c640a
Revises: cfb487136f33
Create Date: 2020-11-03 11:53:56.038651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8cb141c640a'
down_revision = 'cfb487136f33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billdebts', sa.Column('payer_screen_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billdebts', 'payer_screen_name')
    # ### end Alembic commands ###
