"""empty message

Revision ID: f9bd8295992f
Revises: 6e1c55e8dfc7
Create Date: 2020-10-29 09:30:01.082603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9bd8295992f'
down_revision = '6e1c55e8dfc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bills',
    sa.Column('billid', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('statusid', sa.Integer(), nullable=True),
    sa.Column('payeeid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('amount_bill', sa.Numeric(), nullable=True),
    sa.Column('amount_total', sa.Numeric(), nullable=True),
    sa.Column('filefolder', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['payeeid'], ['users.userid'], ),
    sa.PrimaryKeyConstraint('billid')
    )
    op.create_table('billdebts',
    sa.Column('billdebtid', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('statusid', sa.Integer(), nullable=True),
    sa.Column('payerid', sa.Integer(), nullable=False),
    sa.Column('amount_owed', sa.Numeric(), nullable=True),
    sa.Column('billid', sa.Integer(), nullable=True),
    sa.Column('invoiceid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['billid'], ['bills.billid'], ),
    sa.ForeignKeyConstraint(['invoiceid'], ['invoices.invoiceid'], ),
    sa.ForeignKeyConstraint(['payerid'], ['users.userid'], ),
    sa.PrimaryKeyConstraint('billdebtid')
    )
    op.create_table('receipts',
    sa.Column('receiptid', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('statusid', sa.Integer(), nullable=True),
    sa.Column('billid', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('ownerid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['billid'], ['bills.billid'], ),
    sa.ForeignKeyConstraint(['ownerid'], ['users.userid'], ),
    sa.PrimaryKeyConstraint('receiptid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receipts')
    op.drop_table('billdebts')
    op.drop_table('bills')
    # ### end Alembic commands ###
